---
version: '3'
services:
  app:
    image: react-app
    volumes:
      - app:/app
  nginx:
    image: react-nginx
    ports:
      - "8000:80"
    volumes:
      - app:/react-app
    depends_on:
      - 'app'
volumes:
  app:
